<?php

/*
 * @file
 * Poly Attribute module.
 *
 * Provides the ability to use field tokens for ubercart attribute options.
*
*/

/**
  * Implement hook_help()
 */ 

 function poly_attribute_help($path, $arg) {
 switch ($path) {
 case 'admin/help#poly_attribute':
   $output = '';
   $output .= '<h3>' . t('About Poly Attribute') . '</h3>';
   $output .= '<p>' . t("The Poly Attribute modules enable you to use tokens for replacement of attribute options hence making it attibut option dynamic") . '<p>';
 return $output;
   }
 }

/**
  * Implement hook_form_alter()
  * provides token support for ubercart attribute options
  */ 
 
 function poly_attribute_form_uc_attribute_uc_form_alter(&$form, &$form_state, $form_id) {
 dsm($form);
  if (module_exists('token')) {
   $form['token_help'] = array(
     '#theme' => 'token_tree',
    '#token_types' => array('node'),
  );
 }
 
}

 function poly_attribute_custom_submit() {
  
}
